<a href="https://colab.research.google.com/github/parismoscow/Alzheimer-s_Disease/blob/master/Alzheimers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# !pip install imblearn

  Found existing installation: scikit-learn 0.20.1
    Uninstalling scikit-learn-0.20.1:
      Successfully uninstalled scikit-learn-0.20.1


Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'C:\\Users\\jasmi\\AppData\\Local\\Temp\\pip-uninstall-2wmacsb6\\users\\jasmi\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gradient_boosting.cp37-win_amd64.pyd'
Consider using the `--user` option or check the permissions.



In [1]:
import pandas as pd
# import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
# from sklearn.preprocessing import MinMaxScaler
# from sklearn.preprocessing import StandardScaler
# from sklearn.model_selection import GridSearchCV
# from sklearn.ensemble import RandomForestClassifier
# from imblearn.over_sampling import SMOTE
# from imblearn.over_sampling import RandomOverSampler
# from sklearn.decomposition import PCA
# from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
# from sklearn.linear_model import LogisticRegression
# from sklearn.preprocessing import LabelEncoder
# from collections import Counter
import ad_tools as adt
import pickle



In [2]:
# Run this cell to mount your Google Drive.
# from google.colab import drive
# drive.mount('/content/drive')

ModuleNotFoundError: No module named 'google.colab'

In [87]:
# df = pd.read_csv("/content/drive/My Drive/measures.csv")
# df = pd.read_csv("/content/drive/My Drive/pct_changes.csv")
# choose either 'DX' or 'DXCHANGE' for prediction
# df = pd.read_csv("/content/drive/My Drive/TADPOLE_D1_D2.csv").loc[:, ["PTID", "DX", "PTEDUCAT", "ADAS13", "Ventricles", "CDRSB", "ADAS11", "MMSE",  "RAVLT_immediate", "Hippocampus", "WholeBrain", "Entorhinal", "MidTemp"]]
# df = pd.read_csv("/content/drive/My Drive/TADPOLE_D1_D2.csv").loc[:, ["PTID", "DX", "PTGENDER", "PTEDUCAT", "ADAS13", "Ventricles", "CDRSB", "ADAS11", "MMSE",  "RAVLT_immediate", "Hippocampus", "WholeBrain", "Entorhinal", "MidTemp", "FDG", "AV45", "ABETA_UPENNBIOMK9_04_19_17", "TAU_UPENNBIOMK9_04_19_17", "PTAU_UPENNBIOMK9_04_19_17", "APOE4"]]
# df = pd.read_csv("/content/drive/My Drive/TADPOLE_D1_D2.csv").loc[:, ["PTID", "DX", "AGE",  "PTRACCAT", "PTETHCAT", "PTGENDER", "PTEDUCAT", "APOE4", "Ventricles", "CDRSB", "ADAS11", "MMSE", "ADAS13", "RAVLT_immediate",  "Hippocampus", "WholeBrain", "Entorhinal", "MidTemp"]]
# df = pd.read_csv("/content/drive/My Drive/TADPOLE_D1_D2.csv").loc[:, ["PTID", "DX", "PTRACCAT", "PTETHCAT", "PTGENDER", "PTEDUCAT", "ADAS13", "Ventricles", "CDRSB", "ADAS11", "MMSE",  "RAVLT_immediate", "Hippocampus", "WholeBrain", "Entorhinal", "MidTemp", "FDG", "AV45", "ABETA_UPENNBIOMK9_04_19_17", "TAU_UPENNBIOMK9_04_19_17", "PTAU_UPENNBIOMK9_04_19_17", "APOE4"]]
# df = pd.read_csv("/content/drive/My Drive/TADPOLE_D1_D2.csv").loc[:, ["PTID", "DX", "AGE",  "PTRACCAT", "PTETHCAT", "PTGENDER", "PTEDUCAT", "APOE4", "Ventricles", "CDRSB", "ADAS11", "MMSE", "ADAS13", "RAVLT_immediate",  "Hippocampus", "WholeBrain", "Entorhinal", "MidTemp", "FDG", "AV45", "ABETA_UPENNBIOMK9_04_19_17", "TAU_UPENNBIOMK9_04_19_17", "PTAU_UPENNBIOMK9_04_19_17"]]

df = pd.read_csv("/content/drive/My Drive/TADPOLE_D1_D2.csv").loc[:, ["PTID", "DX", "AGE", "PTRACCAT", "PTETHCAT", "PTGENDER", "PTEDUCAT", "APOE4"]]

# df.head()



/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (471,473,474,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,569,570,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,599,601,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,624,625,626,627,628,629,630,631,632,633,634,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724

In [0]:
# df.shape[0]

In [0]:
# df['DX'].value_counts()

In [0]:
# drop = True
# df = adt.cleanup_data(df, drop)

In [0]:
# df = df.groupby('PTID').apply(adt.add_pct_change, ['Ventricles', 'Hippocampus', 'WholeBrain', 'Entorhinal', 'MidTemp'])
# df = df.groupby('PTID').apply(adt.add_sum_column)
# df = df.groupby('PTID').apply(adt.add_final_dx_column)
# df = df.groupby('PTID').apply(add_pct_change, ["ADAS13", "CDRSB", "ADAS11", "MMSE", "RAVLT_immediate"])


In [0]:
# df.shape[0]

In [0]:
# adt.show_data(df, 'DX')

In [0]:
# df.to_csv("demographic_apoe4_cogtest_MRIpc_PET_CSF.csv", index=False)


In [13]:
df = pd.read_csv("Data/demographic_apoe4_cogtest_MRIpc_PET_CSF.csv")

In [14]:
df.head(100)

df['DX'].value_counts()


MCI         425
NL          281
Dementia    107
Name: DX, dtype: int64

In [15]:
X, y = adt.populate_X_y (df, 'DX', ["PTRACCAT", "PTETHCAT", "PTGENDER"])

Split data into train and test

In [16]:
X_train, X_test, y_train, y_test = train_test_split (X, y, random_state=42)

PCA

In [0]:
# X_train, X_test = adt.myPCA (X_train, X_test)

Scale the features

In [17]:
X_train, X_test = adt.scale_features ('standard', X_train, X_test)

In [18]:
# oversample using SMOTE or random
X_train, y_train = adt.oversample ('smote', X_train, y_train)

Resampled dataset shape Counter({'MCI': 317, 'NL': 317, 'Dementia': 317})


In [0]:
# pickle.dump(model, open('rf_demographic_apoe4_cogtest_MRIpc_PET_CSF.sav', 'wb'))


In [22]:
filename = 'Models/rf_demographic_apoe4_cogtest_MRIpc_PET_CSF.sav'
model = pickle.load(open(filename, 'rb'))
print(model.score(X_test, y_test), "\n")
predictions = model.predict(X_test)
print ("\nUsing", len(X_train), "samples for training")

print ("\nConfusion matrix\n", confusion_matrix(y_test, predictions))
print("\n", classification_report(y_test, predictions))

0.9313725490196079 


Using 951 samples for training

Confusion matrix
 [[ 22   3   0]
 [  5 101   2]
 [  0   4  67]]

               precision    recall  f1-score   support

    Dementia       0.81      0.88      0.85        25
         MCI       0.94      0.94      0.94       108
          NL       0.97      0.94      0.96        71

    accuracy                           0.93       204
   macro avg       0.91      0.92      0.91       204
weighted avg       0.93      0.93      0.93       204



Select and run a model

In [19]:
# model = adt.run_model('random forest', X_train, X_test, y_train, y_test)
# # probas[0:10]

************* random forest *************
 
Score is:  0.9215686274509803 


Confusion matrix
 [[22  3  0]
 [ 6 99  3]
 [ 0  4 67]]

               precision    recall  f1-score   support

    Dementia       0.79      0.88      0.83        25
         MCI       0.93      0.92      0.93       108
          NL       0.96      0.94      0.95        71

    accuracy                           0.92       204
   macro avg       0.89      0.91      0.90       204
weighted avg       0.92      0.92      0.92       204



In [0]:
# import matplotlib.pyplot as plt
# probas = model.predict_proba(X_test)
# # probas
# plt.figure(dpi=150)
# plt.hist(probas, bins=20)
# plt.title('Classification Probabilities')
# plt.xlabel('Probability')
# plt.ylabel('# of Instances')
# plt.xlim([0.5, 1.0])
# target_names = ["Dementia", "MCI", "NL"]
# plt.legend(target_names)
# plt.show()

In [0]:

feature_list = list(X.columns)
# Import tools needed for visualization
from sklearn.tree import export_graphviz
import pydot

# Pull out one tree from the forest
tree = model.estimators_[0]

# Export the image to a dot file
export_graphviz(tree, out_file = 'tree.dot', feature_names = feature_list, rounded = True, precision = 1)

# Use dot file to create a graph
(graph, ) = pydot.graph_from_dot_file('tree.dot')

# Write graph to a png file
graph.write_png('small-tree1.png')

In [0]:
X_features = X.columns


In [78]:
importances = model.feature_importances_
sorted(zip(model.feature_importances_, X_features), reverse=True)



[(0.3355390075821969, 'CDRSB'),
 (0.11666575778665449, 'MMSE'),
 (0.10730456649147746, 'ADAS13'),
 (0.09012826861651854, 'ADAS11'),
 (0.057877803254919674, 'RAVLT_immediate'),
 (0.04603672659454931, 'FDG'),
 (0.030462208513210222, 'AV45'),
 (0.030409538966399863, 'ABETA_UPENNBIOMK9_04_19_17'),
 (0.026840162365283485, 'Hippocampus'),
 (0.021803375210714702, 'AGE'),
 (0.019377587978160728, 'Entorhinal'),
 (0.017039066780720674, 'PTAU_UPENNBIOMK9_04_19_17'),
 (0.01703795414742583, 'TAU_UPENNBIOMK9_04_19_17'),
 (0.016370171869362585, 'Ventricles'),
 (0.01453879915417097, 'MidTemp'),
 (0.013218681751585087, 'WholeBrain'),
 (0.009620748286543314, 'PTEDUCAT'),
 (0.008737150096406975, 'APOE4'),
 (0.0038308284096831868, 'PTGENDER'),
 (0.0031219615666063403, 'pct_MidTemp'),
 (0.002958321919169551, 'PTRACCAT'),
 (0.002938366674358157, 'pct_Entorhinal'),
 (0.002308162986909878, 'pct_Hippocampus'),
 (0.002090176127358075, 'pct_Ventricles'),
 (0.0017685453354797714, 'pct_WholeBrain'),
 (0.0015304159

In [80]:

len(X_features)

27

In [79]:
X_features

Index(['AGE', 'PTRACCAT', 'PTETHCAT', 'PTGENDER', 'PTEDUCAT', 'APOE4',
       'Ventricles', 'CDRSB', 'ADAS11', 'MMSE', 'ADAS13', 'RAVLT_immediate',
       'Hippocampus', 'WholeBrain', 'Entorhinal', 'MidTemp', 'FDG', 'AV45',
       'ABETA_UPENNBIOMK9_04_19_17', 'TAU_UPENNBIOMK9_04_19_17',
       'PTAU_UPENNBIOMK9_04_19_17', 'pct_Ventricles', 'pct_Hippocampus',
       'pct_WholeBrain', 'pct_Entorhinal', 'pct_MidTemp', 'pct_sum'],
      dtype='object')

DNN


In [81]:
from keras.models import Sequential
from keras.layers import Dense

def build_NN_classifier():
    classifier = Sequential()
    classifier.add(Dense(units=6, activation='relu', input_dim=27))
    classifier.add(Dense(units=6, activation='relu'))
    classifier.add(Dense(units=6, activation='relu'))
    classifier.add(Dense(units=6, activation='relu'))
    classifier.add(Dense(units=4, activation='relu'))
    classifier.add(Dense(units=4, activation='relu'))
    classifier.add(Dense(units=4, activation='relu'))
    classifier.add(Dense(units=4, activation='relu'))

    classifier.add(Dense(units=3, activation='softmax'))
    
#     classifier.add(Dense(units=2, activation='relu', input_dim=22))
#     classifier.add(Dense(units=3, activation='softmax'))
    # classifier.summary()
    classifier.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    return classifier

# Create a Keras model that's compatible with scikit-learn
from keras.callbacks import EarlyStopping
from keras.wrappers.scikit_learn import KerasClassifier
keras_NN_classifier = KerasClassifier(build_NN_classifier, epochs=300, shuffle=True, verbose=2, callbacks=[EarlyStopping(monitor='acc', patience=20, verbose=2)])

Using TensorFlow backend.


In [0]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
# from sklearn.decomposition import PCA
# from imblearn.over_sampling import SMOTE

# pca = PCA()
# smt = SMOTE(random_state=42)

# deep_model = make_pipeline(StandardScaler(), smt, pca, keras_NN_classifier)
model = make_pipeline(StandardScaler(), keras_NN_classifier)

In [83]:
model.fit(X_train, y_train)

W0701 22:15:50.087455 140019794884480 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0701 22:15:50.103666 140019794884480 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0701 22:15:50.106137 140019794884480 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0701 22:15:50.221170 140019794884480 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0701 22:15:50.244669 140019794884480 deprecation_wrappe

Epoch 1/300
 - 2s - loss: 1.1004 - acc: 0.3291
Epoch 2/300
 - 0s - loss: 1.0981 - acc: 0.3649
Epoch 3/300
 - 0s - loss: 1.0965 - acc: 0.3964
Epoch 4/300
 - 0s - loss: 1.0887 - acc: 0.4175
Epoch 5/300
 - 0s - loss: 1.0710 - acc: 0.4164
Epoch 6/300
 - 0s - loss: 1.0427 - acc: 0.4332
Epoch 7/300
 - 0s - loss: 1.0106 - acc: 0.4501
Epoch 8/300
 - 0s - loss: 0.9805 - acc: 0.4900
Epoch 9/300
 - 0s - loss: 0.9580 - acc: 0.4753
Epoch 10/300
 - 0s - loss: 0.9295 - acc: 0.4995
Epoch 11/300
 - 0s - loss: 0.9069 - acc: 0.5058
Epoch 12/300
 - 0s - loss: 0.8880 - acc: 0.5205
Epoch 13/300
 - 0s - loss: 0.8721 - acc: 0.5247
Epoch 14/300
 - 0s - loss: 0.8563 - acc: 0.5258
Epoch 15/300
 - 0s - loss: 0.8413 - acc: 0.5300
Epoch 16/300
 - 0s - loss: 0.8272 - acc: 0.5321
Epoch 17/300
 - 0s - loss: 0.8134 - acc: 0.5342
Epoch 18/300
 - 0s - loss: 0.8005 - acc: 0.5889
Epoch 19/300
 - 0s - loss: 0.7882 - acc: 0.6909
Epoch 20/300
 - 0s - loss: 0.7766 - acc: 0.6898
Epoch 21/300
 - 0s - loss: 0.7675 - acc: 0.6898
E

Pipeline(memory=None,
         steps=[('standardscaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('kerasclassifier',
                 <keras.wrappers.scikit_learn.KerasClassifier object at 0x7f58b4482128>)],
         verbose=False)

In [0]:
model_accuracy = model.score(X_test, y_test)
print("Deep Neural Network - Accuracy: {}".format(model_accuracy))

In [0]:
predictions = model.predict(X_test)
print ("\nUsing", len(X_train), "samples for training")
print ("\nConfusion matrix\n", confusion_matrix(y_test, predictions))
print("\n", classification_report(y_test, predictions))